package com.example.androidroommvc;


import androidx.room.Entity;
import androidx.room.PrimaryKey;

//Entity is a room anotation..At run time this  code will be converted into sqlite table
@Entity(tableName = "note_table")
public class Note {

    //these entities will be converted into rows

    @PrimaryKey(autoGenerate = true)
    private int id;

    private String title;

    private String description;
    //columinfo helps to change the row name
    // @ColumnInfo(name = "Priority Comulm")
    private int priority;

    //id is autogenerated so it was not added in the constructor
    public Note(String title, String description, int priority) {
        this.title = title;
        this.description = description;
        this.priority = priority;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getId() {
        return id;
    }

    public String getTitle() {
        return title;
    }

    public String getDescription() {
        return description;
    }

    public int getPriority() {
        return priority;
    }

}
